In [32]:
import numpy as np

## Array Operations


In [33]:
a = [1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [34]:
arr = np.array(a)
print('Array using List: ', arr)

Array using List:  [1 2 3 4 5]


In [35]:
arr = np.random.randint(1,100,20)
print('Array using Random :', arr)

Array using Random : [94 43 14  2 75 97 31 95 69 54 39 24  1 98 46 71 61 39 43 87]


In [36]:
a1 = [1,2,3,4,5]
a2 = [6,7,8,9,10]
result = []

for i in range(len(a1)):
    result.append(a1[i]+a2[i]) 

print(result)

[7, 9, 11, 13, 15]


In [37]:
a1 = np.random.randint(1,100,10)
a2 = np.random.randint(1,100,10)

print('Array 1 :',a1)
print('Array 2 :',a2)
print('Addition :',a1+a2)
print('Subtraction :',a1-a2)
print('Power :',a1**a2)
print('Multiplication :',a1*a2)
print('Division :',a1/a2)
print('Floor Division :',a1//a2)


Array 1 : [ 4 14 40 61 14 45 93 10 44 37]
Array 2 : [66 14 22 93 91 27 84 76 75 30]
Addition : [ 70  28  62 154 105  72 177  86 119  67]
Subtraction : [-62   0  18 -32 -77  18   9 -66 -31   7]
Power : [          0 -1282129920           0  -623292755           0  2053019349
 -2104349167           0           0 -2069953943]
Multiplication : [ 264  196  880 5673 1274 1215 7812  760 3300 1110]
Division : [0.06060606 1.         1.81818182 0.65591398 0.15384615 1.66666667
 1.10714286 0.13157895 0.58666667 1.23333333]
Floor Division : [0 1 1 0 0 1 1 0 0 1]


In [38]:
print('Array : ',a1)
print(a1.shape)
print(a1.ndim)
print(a1.size)
print(a1.dtype)

Array :  [ 4 14 40 61 14 45 93 10 44 37]
(10,)
1
10
int32


## Array Creation


In [39]:
print('Ones :',np.ones(5))
print('2D Ones :',np.ones((2, 5)))
print('--------------------------------')
print('Zeros :',np.zeros(5))
print('2D Zeros :',np.zeros((2, 5)))

Ones : [1. 1. 1. 1. 1.]
2D Ones : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
--------------------------------
Zeros : [0. 0. 0. 0. 0.]
2D Zeros : [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [40]:
arr = np.arange(0,10)
print('Range :',arr)
arr = np.arange(0,21,2)
print('Range with step Value :', arr)

Range : [0 1 2 3 4 5 6 7 8 9]
Range with step Value : [ 0  2  4  6  8 10 12 14 16 18 20]


In [41]:
arr = np.linspace(0,10)
print('Linspace :',arr)
arr = np.linspace(0,20,6)
print('Linspace with Range :',arr)

Linspace : [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
Linspace with Range : [ 0.  4.  8. 12. 16. 20.]


## Random


In [42]:
print('Random :',np.random.rand(5))
print('Random Integer :', np.random.randint(1,100,10))
print('Random N:',np.random.randn(10))


Random : [0.50386307 0.19735372 0.77236594 0.89631989 0.7546391 ]
Random Integer : [ 2 96 32 94 17 35 11  1 20 47]
Random N: [ 0.98450575 -0.82424318 -0.52110397 -0.09257848  0.50437507 -0.22705918
 -1.20965174 -0.87194222 -0.35674907  1.14469762]


## Indexing


In [43]:
arr = np.random.randint(1,10,5)
print('Array :',arr)
print('Element on 2nd Index :',arr[2])

print('--------------------------------')

arr = np.random.randint(1,10,size=(3,4))
print('2D Array :\n',arr)
print('Element in 2,3 :',arr[2][3])

Array : [1 6 6 7 5]
Element on 2nd Index : 6
--------------------------------
2D Array :
 [[7 7 9 5]
 [2 2 7 4]
 [6 7 4 1]]
Element in 2,3 : 1


## Slicing


In [44]:
arr = np.random.randint(1,10,5)
print('Array :',arr)
print('Elements from 2nd Index :',arr[2:])
print('Elements from 2nd - 3th Index :',arr[2:4])
print('Elements from 2nd - 3th Index :',arr[2:4])
print('Alternate Elements :',arr[::2])
print('Index Selection :', arr[[0,2,4]])


Array : [3 7 6 1 5]
Elements from 2nd Index : [6 1 5]
Elements from 2nd - 3th Index : [6 1]
Elements from 2nd - 3th Index : [6 1]
Alternate Elements : [3 6 5]
Index Selection : [3 6 5]


In [45]:
arr = np.random.randint(1,10,size=(3,4))
print('2D Array :',arr)
print('Slicing :',arr[:,2])

2D Array : [[7 4 5 3]
 [3 1 9 6]
 [3 5 6 1]]
Slicing : [5 9 6]


In [46]:
arr = np.random.randint(1,10,size=(3,4))
print('2D Array :\n',arr)
print('Slicing - Negative Indexing :',arr[:,-1])

2D Array :
 [[3 4 5 1]
 [5 4 7 4]
 [3 5 8 2]]
Slicing - Negative Indexing : [1 4 2]


## Boolean Indexing


In [47]:
arr = np.random.randint(1,10,5)
print('Array :',arr)
print('Greater than 5 :', arr>5)

Array : [8 5 2 7 7]
Greater than 5 : [ True False False  True  True]


In [48]:
arr = np.random.randint(1,10,5)
print('Array :',arr)
print('Elements Divisible by 2 :', arr[arr%2==0])

Array : [8 9 1 3 7]
Elements Divisible by 2 : [8]


## Mathematical Operations


In [49]:
arr = np.random.randint(1,10,5) 
print('Array :',arr)
print('Addition :',arr+10) # Scalar Broadcasting

Array : [7 7 9 2 5]
Addition : [17 17 19 12 15]


In [50]:
arr1 = np.random.randint(1,10,size=(3,4))
print('Array 1 :\n',arr1,"\n")

arr2 = np.random.randint(1,10,size=(3,4))
print('Array 2 :\n',arr2,"\n")

print('Addition :\n',arr1+arr2,"\n") # Row broadcasting
print('Subtraction :\n',arr1-arr2,"\n") # Row broadcasting

Array 1 :
 [[2 4 4 8]
 [6 7 4 8]
 [4 3 5 1]] 

Array 2 :
 [[3 8 8 4]
 [4 3 7 3]
 [3 4 3 2]] 

Addition :
 [[ 5 12 12 12]
 [10 10 11 11]
 [ 7  7  8  3]] 

Subtraction :
 [[-1 -4 -4  4]
 [ 2  4 -3  5]
 [ 1 -1  2 -1]] 



In [51]:
arr1 = np.random.randint(1, 10, size=(3, 4))
arr2 = np.random.randint(1, 10, size=(4, 3))

print('Array 1:\n', arr1, "\n")
print('Array 2:\n', arr2, "\n")

Array 1:
 [[1 4 4 7]
 [9 9 3 4]
 [4 8 2 4]] 

Array 2:
 [[4 7 4]
 [7 5 6]
 [1 8 6]
 [1 7 5]] 



In [52]:
print('Matrix Multiplication using @:\n', arr1 @ arr2, "\n")
print('Matrix Multiplication using np.dot:\n', np.dot(arr1, arr2), "\n")
print('Matrix Multiplication using np.matmul:\n', np.matmul(arr1, arr2), "\n")

Matrix Multiplication using @:
 [[ 43 108  87]
 [106 160 128]
 [ 78 112  96]] 

Matrix Multiplication using np.dot:
 [[ 43 108  87]
 [106 160 128]
 [ 78 112  96]] 

Matrix Multiplication using np.matmul:
 [[ 43 108  87]
 [106 160 128]
 [ 78 112  96]] 



### Square, Absolute, Log, Exponential


In [53]:
arr = np.random.randint(1, 10, size=(3, 4))
print('Array :\n',arr,'\n')

print('Square :\n',np.sqrt(arr),'\n')
print('Absolute :\n',np.abs(arr),'\n')
print('Log :\n',np.log(arr),'\n')
print('Exponential :\n',np.exp(arr),'\n')


Array :
 [[5 7 1 8]
 [7 5 6 7]
 [1 7 9 7]] 

Square :
 [[2.23606798 2.64575131 1.         2.82842712]
 [2.64575131 2.23606798 2.44948974 2.64575131]
 [1.         2.64575131 3.         2.64575131]] 

Absolute :
 [[5 7 1 8]
 [7 5 6 7]
 [1 7 9 7]] 

Log :
 [[1.60943791 1.94591015 0.         2.07944154]
 [1.94591015 1.60943791 1.79175947 1.94591015]
 [0.         1.94591015 2.19722458 1.94591015]] 

Exponential :
 [[1.48413159e+02 1.09663316e+03 2.71828183e+00 2.98095799e+03]
 [1.09663316e+03 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.71828183e+00 1.09663316e+03 8.10308393e+03 1.09663316e+03]] 



## Statistical Operations


In [54]:
arr = np.random.randint(1,100,5) 
print('Array :',arr,'\n')

print('Mean :',np.mean(arr))
print('Median :',np.median(arr))
print('Standard Deviation :',np.std(arr))
print('Maximum Value :',np.max(arr))
print('Minimum Value :',np.min(arr))
print('Percentile :',np.percentile(arr,25))


Array : [69 59 89 44  8] 

Mean : 53.8
Median : 59.0
Standard Deviation : 27.169100095512917
Maximum Value : 89
Minimum Value : 8
Percentile : 44.0


In [55]:
print("argmax",np.argmax(a))
print("mean",np.mean(a))
print("median",np.median(a))
print("std",np.std(a))
print("var0",np.var(a))
print("max",np.max(a))
print("min",np.min(a))
print("percent",np.percentile(a,100))
print("argmin",np.argmin(a))
print("argmax",np.argmax(a))
b=np.array([1,2,3,45])
c=np.array([2,4,5,6])
print("cor",np.corrcoef(b,c))

argmax 4
mean 3.0
median 3.0
std 1.4142135623730951
var0 2.0
max 5
min 1
percent 5.0
argmin 0
argmax 4
cor [[1.         0.70985277]
 [0.70985277 1.        ]]


1. Create 2D NumPy array of student scores; compute class average, highest scorer, normalize scores to 0-1 range


In [56]:
score = np.random.randint(1,101,size=(10,5))
print('Scores :\n',score,'\n')

student_total_score = np.sum(score, axis=1)
print('Student Total Score : \n',student_total_score,'\n')

Scores :
 [[10 76 82 49 85]
 [94 70 60 84 10]
 [34 18 31 83 77]
 [39 19 48 64 51]
 [26 30 61 25 13]
 [45 15 31 54 33]
 [48 52 15 55 77]
 [70 65 87 48  8]
 [ 5 63 93 77 17]
 [30 40 90 22 29]] 

Student Total Score : 
 [302 318 243 221 155 178 247 278 255 211] 



In [57]:
print('Highest Score :', np.max(student_total_score))
print('Lowest Score :', np.min(student_total_score))
print('Class Average Score :', np.mean(student_total_score))

Highest Score : 318
Lowest Score : 155
Class Average Score : 240.8


In [58]:
print('Student Highest Score :', np.max(score, axis=1))
print('Student Lowest Score :', np.min(score, axis=1))
print('Student Average Score :', np.mean(score, axis=1))

Student Highest Score : [85 94 83 64 61 54 77 87 93 90]
Student Lowest Score : [10 10 18 19 13 15 15  8  5 22]
Student Average Score : [60.4 63.6 48.6 44.2 31.  35.6 49.4 55.6 51.  42.2]


In [59]:
print('Subject Highest Score :', np.max(score, axis=0))
print('Subject Lowest Score :', np.min(score, axis=0))
print('Subject Average Score :', np.mean(score, axis=0))

Subject Highest Score : [94 76 93 84 85]
Subject Lowest Score : [ 5 15 15 22  8]
Subject Average Score : [40.1 44.8 59.8 56.1 40. ]


In [60]:
normalized_score = (score - np.min(score)) / (np.max(score) - np.min(score))
print('Normalized Score :\n',normalized_score,'\n')

Normalized Score :
 [[0.05617978 0.79775281 0.86516854 0.49438202 0.8988764 ]
 [1.         0.73033708 0.61797753 0.88764045 0.05617978]
 [0.3258427  0.14606742 0.29213483 0.87640449 0.80898876]
 [0.38202247 0.15730337 0.48314607 0.66292135 0.51685393]
 [0.23595506 0.28089888 0.62921348 0.2247191  0.08988764]
 [0.4494382  0.11235955 0.29213483 0.5505618  0.31460674]
 [0.48314607 0.52808989 0.11235955 0.56179775 0.80898876]
 [0.73033708 0.6741573  0.92134831 0.48314607 0.03370787]
 [0.         0.65168539 0.98876404 0.80898876 0.13483146]
 [0.28089888 0.39325843 0.95505618 0.19101124 0.26966292]] 



2. Given arr = np.array([10,20,30,40,50]), write NumPy expressions to get all elements > 25 and compute their sum


In [61]:
arr = np.array([10,20,30,40,50])
print('Array :',arr,'\n')

print('Sum of Elements > 25:',np.sum(arr[arr>25]))

Array : [10 20 30 40 50] 

Sum of Elements > 25: 120


3. Give an example where a (3,1) array is added to a (1,4) array - what is the output shape?


In [62]:
arr1 = np.random.randint(0,10,size=(3,1))
arr2 = np.random.randint(0,10,size=(1,4))
print(arr1+arr2)

[[10  9 12 12]
 [13 12 15 15]
 [ 6  5  8  8]]
